### ISSUE TITLE
STL casing for Megadesk and Megadesk Companion

### ISSUE THREAD

**Issue by androidand** [gcormier/megadesk_companion#1]
Hi, I've installed the Megadesk and Megadesk Companion on my Bekant and it's great. However, at the moment the Companion PCB is hanging outside of the original casing where the Megadesk PCB sits. 

Is there a way to make the Companion PCB fit in there or any other suggestions? Has anyone made a STL for a casing that would fit the two PCBs and the button board?

**Comment by gcormier** [comment]
I have mine mounted to the outside of the case with double-sided foam mounting tape.

However, I am working on a 3D printed case design. However, I've not yet finished it nor tested it for thermals to make sure the companion does not get too hot.

![image](https://github.com/gcormier/megadesk_companion/assets/8388983/960614d5-7467-48f1-be45-85116c2068ff)

**Comment by androidand** [comment]
I will try to get in contact with you. I can help you test the design if you want.

**Comment by gcormier** [comment]
Case design (Fusion 360) and STL here - https://github.com/gcormier/megadesk_companion/tree/main/case

**Comment by androidand** [comment]
I printed this. It doesn't fit the Megadesk Companion v3 board which I have, this case is too small. I suspect this board is for the Companion v4f PCB? I actually turned that cad file into a STL and printed it too, and that piece fits inside of this casing.

**Comment by gcormier** [comment]
Indeed it is for the V4.

V3 STEP is here - https://github.com/gcormier/megadesk_companion/releases/download/pcb-v3/megadesk_companion-3D.step

**Comment by raleighlittles** [comment]
I just printed this STL and tested it with a Megadesk Companion v4d. It fits, but access to the USB-c port is blocked. I also recommend adding vents along the bottom side for air flow. 

![IMG_0696](https://github.com/gcormier/megadesk_companion/assets/2137201/9af3a9ab-5385-425f-b8ba-5f5ec44a03e7)
![IMG_0697](https://github.com/gcormier/megadesk_companion/assets/2137201/1db982b0-f43d-4583-b77a-1f3b8449e5f6)

**Comment by gcormier** [comment]
v2 of the case now has a cutout for the USB connector and additional ventilation. 

https://github.com/gcormier/megadesk_companion/blob/main/case/companion_case_v2.stl

**Comment by Wummeke** [comment]
Hi Greg, can you share the f3z file for that case too? I want to modify it, since I have smaller screws.

**Comment by gcormier** [comment]
> Hi Greg, can you share the f3z file for that case too? I want to modify it, since I have smaller screws.

Which case?

**Comment by Wummeke** [comment]
> > Hi Greg, can you share the f3z file for that case too? I want to modify it, since I have smaller screws.
> 
> Which case?

For this one: [companion_case_v2.stl](https://github.com/gcormier/megadesk_companion/blob/main/case/companion_case_v2.stl)

**Comment by gcormier** [comment]
Sure! Can you let me know which version is printed on your companion PCB? I'll re-organize the STL and F3D files tomorrow and upload them for the various versions.

**Comment by Wummeke** [comment]
Well... I dont'have my Megadesk & companion yet, but I'm hoping you'll be posting my order very soon ;)

Edit: Ah, I see in my mail you just did! Thanks for your awesome work (y)

**Comment by gcormier** [comment]
In that case you will want the legacy_tall case

https://github.com/gcormier/megadesk_companion/tree/main/case

It has extra room for the bodge capacitor which was needed for some issues.

**Comment by gcormier** [comment]
All cases now here - https://github.com/gcormier/megadesk_companion/tree/main/case
