### ISSUE TITLE
Instructions on how to flash?

### ISSUE THREAD

**Issue by raleighlittles** [gcormier/megadesk_companion#2]
I just received my Megadesk companion and Megadesk board. How do I perform an initial flash of the device via the USB-c port?

**Comment by gcormier** [comment]
https://www.youtube.com/watch?v=hUrNMm47_AY

**Comment by raleighlittles** [comment]
Thanks for the video. I created instructions from the video in the interest of bandwidth.

----

* Start by holding down the center button on your device while you plug in the USB-c cable.

* Open a Linux terminal and run `pip install esphome`

* Run `$ esptool.py chip_id`

Verify the output looks something like -- with no error messages:

![image](https://github.com/gcormier/megadesk_companion/assets/2137201/cf35e601-ddba-4a2e-8da5-d174b379ed73)

* Open `megadesk-companion.yaml` in the `megadesk` repository's `/esphome` directory, go to the section that says "wifi" and edit the file to add your router's SSID and corresponding password.

* Run `$ esphome compile megadesk-companion.yaml` and verify it completes successfully. It should say something like:

```
INFO Successfully compiled program.
```

at the end.

* Run `$ esphome upload megadesk-companion.yaml` then choose 1 at the first option to enable flashing via USB/serial.

Verify the command runs successfully, should indicate 

```
INFO Successfully uploaded program
``` 

at the bottom.
