### ISSUE TITLE
Unable to flash device on Mac

### ISSUE THREAD

**Issue by osb99** [gcormier/megadesk_companion#3]
Hi,
I am unsure how to flash the device on Mac in terminal. When compiling it says:

INFO ESPHome 2023.11.6
INFO Reading configuration megadesk-companion.yaml...
ERROR Error while reading config: Invalid YAML syntax:

Error reading file secrets.yaml: [Errno 2] No such file or directory: 'secrets.yaml'

Any idea how to fix?

Also how do I know what serial the device is on?

**Comment by gcormier** [comment]
You can add in your own hardcoded wifi SSID and password if you want. Or you create a seperate secrets.yaml file in the same directory to put that information. 

Old
```
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```

New
```
wifi:
  ssid: yourSSID
  password: yourWiFiPassword
```

**Comment by gcormier** [comment]
Please continue at https://github.com/gcormier/megadesk/discussions/138 if needed.
