### ISSUE TITLE
WiFi seems to have stopped working

### ISSUE THREAD

**Issue by madnat** [gcormier/megadesk_companion#6]
Have had Megadesk for about a month, quickly got up and running on HomeAssistant and wowing my friends and family with my app driven Megadesk.  

Something has changed recently where the device no longer shows on Home Assistant or ESPHome via WiFi, but does show if I connect via the USB-C connector (assume it is communicating via serial?).  Seems to have changed after rebooting my Home Assistant host machine.

Device flashes ok via Wifi from Home Assistant ESPHome add-in (via HACS), and USB-C with the ESPHome Web flashing tool (serial connection from Chrome).

Chimes work on boot.  LED's light.

But cannot see the device from in Home Assistant Lovelace Card, or "Visit" via ESPHome Add In.

The Device can be Ping'ed via Fing... and has an IP address on my LAN.

Any suggestions?

**Comment by lemmifun** [comment]
I installed the companion   today and it worked for an hour and now I am not able to get access via wifi at a all.
I tried to flash it again which, but the issues remains the same.

**Comment by madnat** [comment]
Had a little more time this morning to check out the Companion PCB.

I decided to delete the device from ESPHome view in Home Assistant.  I reflashed the Megadesk Companion Board with a fresh ESPHome install, and recreated the Megadesk device in ESP Home (again in Home Assistant HACS Add On).  Copied and pasted the relevant parts of Megadesk Companion YAML code into the new device and uploaded.  Secrets did not need to change.

After rebuilding the device and uploading the code to the Mega Desk Companion PCB - the device now seems to be working correctly again.

Perhaps the previous device broke after I upgraded Home Assistant to OS V12.0?
I have these versions of Home Assistant components installed:
Core 2024.2.5
Supervisor 2024.02.1
Operating System 12.0
Frontend 20240207.1

**Comment by lemmifun** [comment]
> I installed the companion today and it worked for an hour and now I am not able to get access via wifi at a all. I tried to flash it again which, but the issues remains the same.

It turns out that I had a special character in my SSID configuration that prevented me to access my  wifi. Problem is resolved.
