### ISSUE TITLE
Feature Request: Save Buttons/API

### ISSUE THREAD

**Issue by WelzelRon** [gcormier/megadesk_companion#8]
Hi,

would it be possible to add save buttons or API?
Because I have the problem if sometimes no power is available Megadesk forget the stored positions.

If this is happen it would be great to simply trigger a shell script with curl-commands to set positions and then save it.
If not I will do it the same way :D but have to press the button manually.

Best regards

**Comment by gcormier** [comment]
Hi - if your megadesk is forgetting the saved memory, please see https://github.com/gcormier/megadesk/discussions/174
