### ISSUE TITLE
Unable to Control Desk via Megadesk Companion (5-Pin Variant)

### ISSUE THREAD

**Issue by jan-muller** [gcormier/megadesk_companion#9]
First of all, thank you for this project. I think it’s really cool that people are turning this idea into a product and also sharing it as open source. 👍

I received my Megadesk + Companion last week. It’s the 5-pin variant. I installed the YAML file using ESPHome, and everything went smoothly. I can access the companion via megadesk.local.

However, I’m unable to control the desk via the companion. When I try to do so through the web interface, I see the following:
![Screenshot 2024-11-21 at 10 50 49](https://github.com/user-attachments/assets/99330b27-ef57-4f57-8e5d-89cfeacfb330)

I also tried using a CURL call, but then I get the following message:
![Screenshot 2024-11-21 at 10 51 39](https://github.com/user-attachments/assets/78572ffa-bf4d-4a1b-8145-07df509d41d5)

I’ve tried to resolve the issue myself using suggestions from the internet, but I haven’t been able to figure it out. Someone knows what might be going wrong and can help me out?

Thanks in advance!

**Comment by gcormier** [comment]
Please open discussion at https://github.com/gcormier/megadesk/discussions
